### ISSUE TITLE
Library uses wyszukiwarkaregontest.stat.gov.pl

### ISSUE THREAD

**Issue by DSpeichert** [freshmindpl/wyszukiwarkaregon#7]
The library upon normal non-sandbox use:

``` php
>>> $client = new Client(['key' => 'correct-prodution-key-here']);
=> WyszukiwarkaRegon\Client {#908}
>>> $client->login();
WyszukiwarkaRegon\Exception\InvalidKeyException with message 'Invalid api key'
```

Always sends requests to `wyszukiwarkaregontest.stat.gov.pl` instead of `wyszukiwarkaregon.stat.gov.pl`.

Version 3.0.1 commit 8c431855daf8e1d8459c4c9c317d20e8606799ae

**Comment by krzaczek** [comment]
What version of PHP are You using ?

``` php
<?php

include 'vendor/autoload.php';

$client = new \WyszukiwarkaRegon\Client(['key' => '123123123']);
$client->login();
```

According to my tests all requests are sent to `https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc`

**Comment by DSpeichert** [comment]
```
PHP 7.0.4 (cli) (built: Mar  5 2016 09:28:27) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Using tcpdump, we only see connections to `wyszukiwarkaregontest.stat.gov.pl` and that explains why a production key is failing with `InvalidKeyException`.

**Comment by krzaczek** [comment]
I haven't tested it on PHP 7.x. On PHP >=5.4 all works OK. I'll have to verify this on PHP7

**Comment by krzaczek** [comment]
@DSpeichert Try adding 

`$this->transport->__setLocation($this->url);`

in `src/Service.php` in `__construct()` at the end.

**Comment by DSpeichert** [comment]
@krzaczek That does not help :/

**Comment by krzaczek** [comment]
@DSpeichert I can't seem to find a reason this is not beeing set. May by a PHP BUG.

A quick and dirty fix is to add
`$location = $this->location;` in `src/Transport.php` line 41

``` php
public function __doRequest($request, $location, $action, $version, $one_way = 0)
    {
        $location = $this->location;
        $response = parent::__doRequest($request, $location, $action, $version);
        if (!$response) {
            return $response;
        }
        $matches = array();
        preg_match('/<s:Envelope.*<\/s:Envelope>/s', $response, $matches);

        return $matches[0];
    }
```

I will have to debug more

**Comment by krzaczek** [comment]
@DSpeichert ok i found it but it will take me some time to prepare it. I don't have time to do it today.

**Comment by DSpeichert** [comment]
@krzaczek Thanks! I'm looking forward to seeing an updated version.

**Comment by krzaczek** [comment]
@DSpeichert version 3.0.2 was published with the fix.
