### ISSUE TITLE
PHP 5.6 - Could not connect to host

### ISSUE THREAD

**Issue by tmdoit-zz** [freshmindpl/wyszukiwarkaregon#9]
Get an error "There was an error: exception 'SoapFault' with message 'Could not connect to host' in ../gusClient/vendor/freshmindpl/wyszukiwarkaregon/src/Transport.php:42". 
Resolved with update to 7.1.

**Comment by mike-code** [comment]
I have the same issue with PHP 7.0

**Comment by krzaczek** [comment]
I'll debug it on monday.

pawel (at) mobile

**Comment by krzaczek** [comment]
Could not reproduce it. Looks like a problem with connection to GUS endpoint. @tmdoit can You reproduce it. If so please send me an example code to make this happen.
